### 2.4. Содержание файла с NumPy

В файле `HW01.ipynb` должны быть:

1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [6]:
import numpy as np

In [10]:
list_array = np.array([1,2,3,4,5])
zeros_array = np.zeros((2,3))
ones_array = np.ones((3,2))
arange_array = np.arange(0,15,2)
list_array

array([1, 2, 3, 4, 5])

In [11]:
ones_array.shape, ones_array.ndim, ones_array.dtype, ones_array.size

((3, 2), 2, dtype('float64'), 6)

In [12]:
list_array[0]

np.int64(1)

In [13]:
list_array[1:4]

array([2, 3, 4])

прибавим в каждому элементу срезу константу. Работаем с копией, исходный массив не меняется. 

In [14]:
list_array[1:4] + 5

array([7, 8, 9])

In [18]:
list_array[1:4], list_array[2:5]

(array([2, 3, 4]), array([3, 4, 5]))

поэлементно перемножим эти срезы

In [17]:
list_array[1:4] * list_array[2:5]

array([ 6, 12, 20])

Получаем средние значения, стандартное отклонение и дисперсию массива.

In [20]:
print(list_array.mean(), list_array.std(), list_array.var())

3.0 1.4142135623730951 2.0
